### PR TITLE
Add HTMX edit row example

### PR DESCRIPTION
**Pull request by davidwilde**
I was the OP of this reddit post -
https://www.reddit.com/r/htmx/comments/16nui5k/concerned_hypersrcipt_could_be_the_barrier_to/ in which I argued that Hyperscript is offputting for people transitioning from the Javascript world having one more thing to learn. In one of the comments for the post, I was made aware of surreal. I thought it looked excellent so I gave it a whirl by modifying the
[Edit Row example](https://htmx.org/examples/edit-row/) on the HTMX site to work with surreal instead of hyperscript

### CODE REVIEW

**Comment by gnat** [comment]
Hey @davidwilde thank you for the wicked example! I've been considering creating a separate `awesome-surreal` repo to link to projects such as these or an Awesome Surreal section on the main repo.

Feel free to host this on your own, may I suggest `surreal-example-htmx-go`? Keeps it google-able.

Also if you wish to keep your repo extra small you can always pull in the CDN: https://cdn.jsdelivr.net/gh/gnat/surreal/surreal.js

**Comment by davidwilde** [comment]
sweet. I'm going to do that. Mainly just wanted to grab your attention with the PR

**Comment by davidwilde** [comment]
I've moved this to https://github.com/davidwilde/surreal-htmx-go and followed your recommendation on using the CDN

**Comment by gnat** [comment]
Amazing. Kicked off the [awesome-surreal](https://github.com/gnat/awesome-surreal) list and added your project.

Thanks again @davidwilde !!

**Comment by davidwilde** [comment]
@gnat, I actually read a bit more of your documentation and improved my example by using `trigger`

**Pull request closed without merging**
